name: CI

on:
  push:
    branches:
      - centos7
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build image
        run: docker build -t tuleap .
      - name: Launch image
        timeout-minutes: 10
        run: docker run --rm -v "$(pwd)/tests/is_tuleap_https_server_up.sh":/is_tuleap_https_server_up.sh tuleap /is_tuleap_https_server_up.sh
